import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { Header } from "./header";
import { Footer } from "./footer";
import { useRouter } from "next/router";

import { api } from "~/utils/api";
import { useEffect } from "react";



export default function Home() {

  const router = useRouter();
  const { status } = useSession();

  useEffect(() => {
    if (status === "authenticated") {
      router.push("/welcome");
    }
  }, [status, router]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[url(/main.svg)] bg-cover bg-center min-h-screen w-full p-28">
        <div className="text-white pb-14">
          <h1 className="text-4xl font-bold pb-1">Как решать задачи <br /> на StudLink</h1>
          <p className="font-bold">Идеально для студентов и компаний</p>
        </div>
        <div className="text-white flex justify-between text-3xl px-7 [&_li]:text-wrap">
          <ul className="list-disc *:pb-12 pe-5">
            <li>Регистрируйтесь как студент</li>
            <li>Откликайтесь на проекты</li>
            <li>Получайте опыт и заработок</li>
            <li>Гибкий график</li>
            <li>Возможность стажировки</li>
          </ul>
          <ul className="list-disc *:pb-12">
            <li>Зарегистрируйтесь как компания</li>
            <li>Размещайте проекты и выбирайте исполнителя</li>
            <li>Удобное управление заказами</li>
            <li>Быстрый отбор кандидатов</li>
            <li>Доступ к мотивированным студентам</li>
          </ul>
        </div>
      </div>
      {/*<div>
        {projects.data?.map((projects) => (<div className="text-black" key={projects.id}>{projects.title}</div>))}
      </div> */}
    </>
  );
}
