import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { Header } from "./header";
import { Footer } from "./footer";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const projects = api.post.getAll.useQuery();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <div className="bg-[url(/main.svg)] bg-cover bg-center min-h-screen w-full p-28">
        <div className="text-white pb-14">
          <h1 className="text-4xl font-bold pb-1">Как решать задачи <br /> на StudLink</h1>
          <p className="font-bold">Идеально для студентов и компаний</p>
        </div>
        <div className="text-white flex justify-between text-3xl px-7">
          <ul className="list-disc *:pb-12">
            <li>Мы крутые</li>
            <li>Лучше чем VK-помойка</li>
            <li>И MAX тоже</li>
            <li>Lorem ipsum dolor sit amet consectetur, adipisicing.</li>
            <li>Lorem ipsum dolor sit amet.</li>
          </ul>
          <ul className="list-disc *:pb-12">
            <li>Lorem ipsum dolor sit.</li>
            <li>Lorem ipsum dolor sit amet.</li>
            <li>Lorem ipsum dolor sit amet consectetur.</li>
            <li>У меня 12 фрагов</li>
            <li>и 10000 урона на бабахе</li>
          </ul>
        </div>
      </div>
      <Footer />
      {/* <AuthShowcase />
      <div>
        {projects.data?.map((projects) => (<div className="text-black" key={projects.id}>{projects.title}</div>))}
      </div> */}
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData,status } = useSession();
  const { data: secretMessage } = api.post.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-black">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
    </div>
  );
}
