import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { Header } from "./header";
import { useRouter } from 'next/navigation'

import { api } from "~/utils/api";
import { useContext, useState } from "react";

export default function Test(){
    const { data: session, status } = useSession();
    return (
        <>
        <Head>
            <title>Create T3 App</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header/>
        <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
            {status == "authenticated" ? <AuthForm/> : <p className="text-white">Login first</p>}
        </main>
        </>
    )
}

export function AuthForm(){
    const router = useRouter();
    const { data: session } = useSession();
    const [title, setTitle] = useState("");
    const [category, setCategory] = useState("");
    const [deadline, setDeadline] = useState("");
    const [budget, setBudget] = useState(0);
    const [description, setDescription] = useState("");
    const companyId = session?.user.id
 
    const { mutate } = api.post.createPost.useMutation({
    onSuccess: () => {
            setTitle("");
            setCategory("");
            setDeadline("");
            setBudget(0);
            setDescription("");
            window.location.href = "/" // костыль, так делать нельзя, но как подругому я не нашёл
        },
    onError: (error) => {
        console.log(`Error creating post: ${error}`)
    }
    })

    return (
        <div className="text-white">
            <input type="text" placeholder="Title" value={title} onChange={
                (e) => setTitle(e.target.value)
            } />
            <select onChange={(e) => setCategory(e.target.value)}>
                <option value="Frontend">Frontend</option>
                <option value="Backend">Backend</option>
                <option value="1C">1C</option>
            </select>
            <input type="datetime-local" onChange={(e) => setDeadline(e.target.value)}/>
            <input type="number" placeholder="Budget" onChange={(e) => setBudget(Number(e.target.value))}/>
            <textarea placeholder="Description" onChange={(e) => setDescription(e.target.value)}></textarea>
            <button onClick={() =>
                {mutate({
                    companyId: session?.user.id ?? "",
                    title: title,
                    deadline: (new Date(deadline)).toISOString(),
                    description: description,
                    budget: budget,
                    category: category,
                })
            }
            }>Submit</button>
        </div>
    )
}

