import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function User() {
  return (
    <>
    <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
        <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
            <AuthShowcase />
        </main>
    </>
  )}

  function AuthShowcase() {
  const { data: sessionData, status} = useSession();
  const user = status == "authenticated" ? api.user.getById.useQuery(sessionData?.user.id) : api.user.getById.useQuery("cmcn5dofo0000xcc4rw8ctwvw") 
  console.log(user)
  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <div>
        {user?.data?.name}
      </div>
      <div>
        {user?.data?.bio}
      </div>
      <div>
        {user?.data?.email}
      </div>
      <div>
        {user?.data?.rating}
      </div>
      <div>
        {user?.data?.role}
      </div>
    </div>
  );
}