import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function User() {
  return (
    <>
    <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
        <main className="flex min-h-screen flex-col items-center justify-center">
            <AuthShowcase />
        </main>
    </>
  )}

  function AuthShowcase() {
  const { data: sessionData, status} = useSession();
  const {data, isLoading: load} = api.user.getById.useQuery(sessionData?.user.id ?? "")
  return (
    <>
      {sessionData?.user.id ? (
        <p>{data?.name}</p>
      ) : (
        <p>Сосал...</p>
      )}
    </>
  );
}